// Generated by gencpp from file miniarm_test/ServoControl.msg
// DO NOT EDIT!


#ifndef MINIARM_TEST_MESSAGE_SERVOCONTROL_H
#define MINIARM_TEST_MESSAGE_SERVOCONTROL_H

#include <ros/service_traits.h>


#include <miniarm_test/ServoControlRequest.h>
#include <miniarm_test/ServoControlResponse.h>


namespace miniarm_test
{

struct ServoControl
{

typedef ServoControlRequest Request;
typedef ServoControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoControl
} // namespace miniarm_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::miniarm_test::ServoControl > {
  static const char* value()
  {
    return "c348f8d8cd3a80f54328aa4159009109";
  }

  static const char* value(const ::miniarm_test::ServoControl&) { return value(); }
};

template<>
struct DataType< ::miniarm_test::ServoControl > {
  static const char* value()
  {
    return "miniarm_test/ServoControl";
  }

  static const char* value(const ::miniarm_test::ServoControl&) { return value(); }
};


// service_traits::MD5Sum< ::miniarm_test::ServoControlRequest> should match
// service_traits::MD5Sum< ::miniarm_test::ServoControl >
template<>
struct MD5Sum< ::miniarm_test::ServoControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::miniarm_test::ServoControl >::value();
  }
  static const char* value(const ::miniarm_test::ServoControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::miniarm_test::ServoControlRequest> should match
// service_traits::DataType< ::miniarm_test::ServoControl >
template<>
struct DataType< ::miniarm_test::ServoControlRequest>
{
  static const char* value()
  {
    return DataType< ::miniarm_test::ServoControl >::value();
  }
  static const char* value(const ::miniarm_test::ServoControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::miniarm_test::ServoControlResponse> should match
// service_traits::MD5Sum< ::miniarm_test::ServoControl >
template<>
struct MD5Sum< ::miniarm_test::ServoControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::miniarm_test::ServoControl >::value();
  }
  static const char* value(const ::miniarm_test::ServoControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::miniarm_test::ServoControlResponse> should match
// service_traits::DataType< ::miniarm_test::ServoControl >
template<>
struct DataType< ::miniarm_test::ServoControlResponse>
{
  static const char* value()
  {
    return DataType< ::miniarm_test::ServoControl >::value();
  }
  static const char* value(const ::miniarm_test::ServoControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINIARM_TEST_MESSAGE_SERVOCONTROL_H
