// Generated by gencpp from file miniarm_test/ServoControlRequest.msg
// DO NOT EDIT!


#ifndef MINIARM_TEST_MESSAGE_SERVOCONTROLREQUEST_H
#define MINIARM_TEST_MESSAGE_SERVOCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace miniarm_test
{
template <class ContainerAllocator>
struct ServoControlRequest_
{
  typedef ServoControlRequest_<ContainerAllocator> Type;

  ServoControlRequest_()
    : command()  {
    }
  ServoControlRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::miniarm_test::ServoControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::miniarm_test::ServoControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServoControlRequest_

typedef ::miniarm_test::ServoControlRequest_<std::allocator<void> > ServoControlRequest;

typedef boost::shared_ptr< ::miniarm_test::ServoControlRequest > ServoControlRequestPtr;
typedef boost::shared_ptr< ::miniarm_test::ServoControlRequest const> ServoControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::miniarm_test::ServoControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::miniarm_test::ServoControlRequest_<ContainerAllocator1> & lhs, const ::miniarm_test::ServoControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::miniarm_test::ServoControlRequest_<ContainerAllocator1> & lhs, const ::miniarm_test::ServoControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace miniarm_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::miniarm_test::ServoControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::miniarm_test::ServoControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::miniarm_test::ServoControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::miniarm_test::ServoControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "miniarm_test/ServoControlRequest";
  }

  static const char* value(const ::miniarm_test::ServoControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::miniarm_test::ServoControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::miniarm_test::ServoControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::miniarm_test::ServoControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIARM_TEST_MESSAGE_SERVOCONTROLREQUEST_H
